version: "3.5"
services:
  postgres:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: spreadsheets-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: spreadsheets
      POSTGRES_PASSWORD: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - 5432:5432
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: "spreadsheets-api"
    image: spreadsheet-api
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/api
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000

volumes:
  postgres:
